version: '3'

services: # 컨테이너들 정의
  demo_nginx: # 컨테이너 이름
    restart: 'always' # 리스타트 정책 no, always, on-failure, unless-stopped
    container_name: 'demo_Nginx'
    build:
      dockerfile: Dockerfile
      context: ./Nginx
    volumes:
      - ./Nginx/logs:/var/log/nginx
    ports:
      - '5008:80' # 호스트 포트:컨테이너 포트
    depends_on:
      - demo_react_front

  demo_react_front: # 컨테이너 이름
    restart: 'on-failure'
    container_name: 'client'
    build:
      dockerfile: Dockerfile # WhatAilsYou_Front_Admin 디렉토리 하위에 Dockerfile을 사용
      context: ./client
    volumes: # 실시간 코드 수정을 위한 volumes 설정
      - '/usr/app/node_modules'
      - './client:/usr/app' # 소스 디렉토리 공유
    expose: # Nginx container에게 노출할 포트
      - 3000
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true # HMR을 위해 필요한 설정
    stdin_open: true # react-script 3.4.1 부터 필요
    tty: true
    command: ['yarn', 'start']
